FORMAT: 1A
HOST: https://onix-codelists.io

# onix-codelists.io

# Onix codelists [/api/v1/codelist]

## Show all codelists [GET /api/v1/codelist{?page,limit,include}]
Get a JSON representation of all Onix codelists.

+ Parameters
    + page (integer, optional) - The page of results to view.
        + Default: 1
    + limit (integer, optional) - The amount of results per page.
        + Default: 25
    + include (enum[enum], optional) - Available additional details to request.
        + Default: codes
        + Members
            + `codes` - The code values that the codelist has

+ Response 200 (application/json)
    + Body

            {
                "id": 1,
                "number": 1,
                "description": "Notification or update type code",
                "issue_number": 0
            }

+ Response 422 (application/json)
    + Body

            {
                "message": "Could not list codelists.",
                "errors": {
                    "page": [
                        "The page must be a number."
                    ]
                },
                "status_code": 422
            }

+ Response 422 (application/json)
    + Body

            {
                "message": "Could not list codelists.",
                "errors": {
                    "page": [
                        "The page must be at least 1."
                    ]
                },
                "status_code": 422
            }

+ Response 422 (application/json)
    + Body

            {
                "message": "Could not list codelists.",
                "errors": {
                    "limit": [
                        "The limit must be a number."
                    ]
                },
                "status_code": 422
            }

+ Response 422 (application/json)
    + Body

            {
                "message": "Could not list codelists.",
                "errors": {
                    "limit": [
                        "The limit must be at least 1."
                    ]
                },
                "status_code": 422
            }

## Show the specified Codelist [GET /api/v1/codelist/{number}?include={include}]
Show a spesific codelist by the codelist number.

+ Parameters
    + number (integer, required) - Number of the codelist
    + include (enum[enum], optional) - Available additional details to request.
        + Default: codes
        + Members
            + `codes` - The code values that the codelist has

+ Response 200 (application/json)
    + Body

            {
                "id": 1,
                "number": 1,
                "description": "Notification or update type code",
                "issue_number": 0
            }

+ Response 422 (application/json)
    + Body

            {
                "message": "Could not list codelist.",
                "errors": {
                    "number": [
                        "The number must be a number."
                    ]
                },
                "status_code": 422
            }

+ Response 422 (application/json)
    + Body

            {
                "message": "Could not list codelist.",
                "errors": {
                    "number": [
                        "The selected number is invalid."
                    ]
                },
                "status_code": 422
            }